@startuml

class Policy {
    .. called through object instance ..
    + forward()
}

class Agent {
    + agent
    + update()
    + action()
    + save_model()
}

class ActorCritic {
    + critic1
    + critic2
    - targetActor
    - targetQ1
    - targetQ2
    + update_critics()
    + update_actor()
    + update_target_networks()
    + get_target_action()
    + get_targetQ1()
    + get_targetQ2()
}

Policy *-- Agent 

Agent <|-- ActorCritic

class Trainer {
    + metrics
    + train()
    + evaluate()
}

Agent *-- Trainer

class ReinforceTrainer {
    + train()
    + evaluate()
}

class TD3Trainer {
    + train()
    + evaluate()
}

Trainer <|-- TD3Trainer

Trainer <|-- ReinforceTrainer

ActorCritic *-- TD3Trainer


class PerformanceMetrics {
    + update_reinforce_trial()
    + update_td3_average()
    + get_reinforce_learning()
    + get_td3_learning()
}

PerformanceMetrics *-- Trainer

class PlotLearningCurve {
    + set_reinforce_data()
    + set_td3_data()
    + plot_learning_curves()
}

@enduml

